apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teste-nginx
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 13.1.5
    chart: nginx
    helm:
      valueFiles:
        - values-helm.yaml
  project: default
