apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  template:
    spec:
      containers:
        - volumeMounts:
          - mountPath: {{ .Values.app.mounted.path }}
            name: secret-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Values.app.mounted.name }}