# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: example
#   namespace: argocd
# spec:
#   generators:
#   - git:
#       repoURL: 'https://github.com/rcustodio2/argo-helm.git'
#       revision: HEAD
#       files:
#       - path: "examples/**.yaml"
#   template:
#     metadata:
#       name: '{{name}}-example'
#     spec:
#       project: default
#       source:
#         helm:
#           # valueFiles:
#           # - values.yaml
#           values: |-
#             {{values}}
#         repoURL: https://github.com/bitnami/charts.git
#         targetRevision: HEAD
#         path: "bitnami/nginx"
#       destination:
#         server: '{{address}}'
#         namespace: default 
---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rodrigo-teste
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/rcustodio2/argo-helm.git'
      revision: HEAD
      files:
      - path: "examples2/**.yaml"  
  template:
    metadata:
      name: '{{name}}-example'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - values.yaml
          # values: |-
          #   {{values}}
        repoURL: https://github.com/bitnami/charts.git
        targetRevision: HEAD
        path: "bitnami/nginx"
      destination:
        server: '{{address}}'
        namespace: default 
